/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module genSky_8 (
    input clk,
    input rst,
    output reg [4:0] sky
  );
  
  
  
  reg [31:0] M_seed_d, M_seed_q = 1'h0;
  wire [32-1:0] M_skynum_num;
  reg [1-1:0] M_skynum_rst;
  reg [1-1:0] M_skynum_next;
  reg [32-1:0] M_skynum_seed;
  pn_gen_13 skynum (
    .clk(clk),
    .rst(M_skynum_rst),
    .next(M_skynum_next),
    .seed(M_skynum_seed),
    .num(M_skynum_num)
  );
  
  always @* begin
    M_seed_d = M_seed_q;
    
    M_skynum_seed = M_seed_q;
    M_skynum_next = 1'h1;
    M_skynum_rst = rst;
    sky = 5'h00;
    M_seed_d = M_seed_q + 1'h1;
    sky = M_skynum_num[0+4-:5];
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_seed_q <= 1'h0;
    end else begin
      M_seed_q <= M_seed_d;
    end
  end
  
endmodule
