/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [1:0] led_r,
    output reg [1:0] led_g,
    output reg [1:0] led_b,
    output reg [3:0] led_addr,
    output reg led_clk,
    output reg led_lat,
    output reg led_blk
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_avr_spi_miso;
  wire [4-1:0] M_avr_spi_channel;
  wire [1-1:0] M_avr_tx;
  wire [1-1:0] M_avr_new_sample;
  wire [10-1:0] M_avr_sample;
  wire [4-1:0] M_avr_sample_channel;
  wire [1-1:0] M_avr_tx_busy;
  wire [8-1:0] M_avr_rx_data;
  wire [1-1:0] M_avr_new_rx_data;
  reg [1-1:0] M_avr_cclk;
  reg [1-1:0] M_avr_spi_mosi;
  reg [1-1:0] M_avr_spi_sck;
  reg [1-1:0] M_avr_spi_ss;
  reg [1-1:0] M_avr_rx;
  reg [4-1:0] M_avr_channel;
  reg [8-1:0] M_avr_tx_data;
  reg [1-1:0] M_avr_new_tx_data;
  reg [1-1:0] M_avr_tx_block;
  avr_interface_2 avr (
    .clk(clk),
    .rst(rst),
    .cclk(M_avr_cclk),
    .spi_mosi(M_avr_spi_mosi),
    .spi_sck(M_avr_spi_sck),
    .spi_ss(M_avr_spi_ss),
    .rx(M_avr_rx),
    .channel(M_avr_channel),
    .tx_data(M_avr_tx_data),
    .new_tx_data(M_avr_new_tx_data),
    .tx_block(M_avr_tx_block),
    .spi_miso(M_avr_spi_miso),
    .spi_channel(M_avr_spi_channel),
    .tx(M_avr_tx),
    .new_sample(M_avr_new_sample),
    .sample(M_avr_sample),
    .sample_channel(M_avr_sample_channel),
    .tx_busy(M_avr_tx_busy),
    .rx_data(M_avr_rx_data),
    .new_rx_data(M_avr_new_rx_data)
  );
  wire [8-1:0] M_register_tx_data;
  wire [1-1:0] M_register_new_tx_data;
  wire [66-1:0] M_register_regOut;
  reg [8-1:0] M_register_rx_data;
  reg [1-1:0] M_register_new_rx_data;
  reg [1-1:0] M_register_tx_busy;
  reg [33-1:0] M_register_regIn;
  reg_interface_3 register (
    .clk(clk),
    .rst(rst),
    .rx_data(M_register_rx_data),
    .new_rx_data(M_register_new_rx_data),
    .tx_busy(M_register_tx_busy),
    .regIn(M_register_regIn),
    .tx_data(M_register_tx_data),
    .new_tx_data(M_register_new_tx_data),
    .regOut(M_register_regOut)
  );
  
  wire [2-1:0] M_matrix_out_r;
  wire [2-1:0] M_matrix_out_g;
  wire [2-1:0] M_matrix_out_b;
  wire [4-1:0] M_matrix_out_addr;
  wire [1-1:0] M_matrix_out_clk;
  wire [1-1:0] M_matrix_out_blk;
  wire [1-1:0] M_matrix_out_lat;
  reg [1-1:0] M_matrix_wr_en;
  reg [11-1:0] M_matrix_wr_addr;
  reg [3-1:0] M_matrix_wr_data;
  led_matrix_4 matrix (
    .clk(clk),
    .rst(rst),
    .wr_en(M_matrix_wr_en),
    .wr_addr(M_matrix_wr_addr),
    .wr_data(M_matrix_wr_data),
    .out_r(M_matrix_out_r),
    .out_g(M_matrix_out_g),
    .out_b(M_matrix_out_b),
    .out_addr(M_matrix_out_addr),
    .out_clk(M_matrix_out_clk),
    .out_blk(M_matrix_out_blk),
    .out_lat(M_matrix_out_lat)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    M_avr_cclk = cclk;
    M_avr_spi_ss = spi_ss;
    M_avr_spi_mosi = spi_mosi;
    M_avr_spi_sck = spi_sck;
    M_avr_rx = avr_tx;
    M_avr_channel = 4'hf;
    M_avr_tx_block = avr_rx_busy;
    spi_miso = M_avr_spi_miso;
    spi_channel = M_avr_spi_channel;
    avr_rx = M_avr_tx;
    M_register_rx_data = M_avr_rx_data;
    M_register_new_rx_data = M_avr_new_rx_data;
    M_avr_tx_data = M_register_tx_data;
    M_avr_new_tx_data = M_register_new_tx_data;
    M_register_tx_busy = M_avr_tx_busy;
    M_register_regIn[32+0-:1] = 1'h0;
    M_register_regIn[0+31-:32] = 32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
    led_r = M_matrix_out_r;
    led_g = M_matrix_out_g;
    led_b = M_matrix_out_b;
    led_addr = M_matrix_out_addr;
    led_clk = M_matrix_out_clk;
    led_lat = M_matrix_out_lat;
    led_blk = M_matrix_out_blk;
    if (M_register_regOut[0+0-:1]) begin
      if (M_register_regOut[1+0-:1]) begin
        M_matrix_wr_en = 1'h1;
        M_matrix_wr_addr = M_register_regOut[2+31-:32];
        M_matrix_wr_data = M_register_regOut[34+0+7-:8];
      end else begin
        M_matrix_wr_en = 1'h0;
        M_matrix_wr_addr = 1'h0;
        M_matrix_wr_data = 1'h0;
      end
    end else begin
      M_matrix_wr_en = 1'h0;
      M_matrix_wr_addr = 1'h0;
      M_matrix_wr_data = 1'h0;
    end
  end
endmodule
