/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module ram_writer_7 (
    input clk,
    input rst,
    output reg [2:0] write_data_top,
    output reg [2:0] write_data_bottom,
    output reg write_en_top,
    output reg write_en_bottom,
    output reg write_address_top,
    output reg write_address_bottom,
    input [2:0] data_read_top,
    input [2:0] data_read_bottom
  );
  
  
  
  localparam INIT_state = 2'd0;
  localparam INIT2_state = 2'd1;
  localparam WRITE_state = 2'd2;
  
  reg [1:0] M_state_d, M_state_q = INIT_state;
  
  always @* begin
    M_state_d = M_state_q;
    
    write_data_top = 1'h0;
    write_data_bottom = 1'h0;
    write_en_top = 1'h0;
    write_en_bottom = 1'h0;
    write_address_top = 1'h0;
    write_address_bottom = 1'h0;
    
    case (M_state_q)
      INIT_state: begin
        write_address_top = 4'h3;
        write_en_top = 1'h1;
        write_data_top = 3'h3;
        write_address_bottom = 4'h1;
        write_en_bottom = 1'h1;
        write_data_bottom = 3'h2;
        M_state_d = INIT2_state;
      end
      INIT2_state: begin
        write_address_top = 4'h7;
        write_en_top = 1'h1;
        write_data_top = 3'h4;
        write_address_bottom = 4'h5;
        write_en_bottom = 1'h1;
        write_data_bottom = 3'h7;
        M_state_d = WRITE_state;
      end
      WRITE_state: begin
        M_state_d = WRITE_state;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
