/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module stateCounterB_15 (
    input clk,
    input rst,
    output reg out1,
    output reg out2
  );
  
  
  
  reg [25:0] M_stateCounter_d, M_stateCounter_q = 1'h0;
  
  always @* begin
    M_stateCounter_d = M_stateCounter_q;
    
    out1 = M_stateCounter_q[24+0-:1];
    out2 = M_stateCounter_q[23+0-:1];
    M_stateCounter_d = M_stateCounter_q + 1'h1;
    if (M_stateCounter_q[24+0-:1] == 1'h1) begin
      M_stateCounter_d[24+0-:1] = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_stateCounter_q <= 1'h0;
    end else begin
      M_stateCounter_q <= M_stateCounter_d;
    end
  end
  
endmodule
